In [22]:
# Numpy

In [23]:
import numpy as np

In [24]:
# Q1

In [25]:
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [26]:
arr=np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [28]:
# Q2

In [29]:
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [30]:
# Q3

In [31]:
randNum = np.random.rand()
print(randNum)

0.5478351376037405


In [32]:
# Q4

In [51]:
import os

arr = np.random.rand(9)
# print(arr)

arr_2d=np.reshape(arr, (3,3))
print(arr_2d)


header = 'col1 col2 col3'
np.savetxt('temp.txt', arr_2d, fmt="%f", header=header) 


print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)



[[0.09664798 0.14642165 0.10788542]
 [0.19427036 0.35002438 0.34483879]
 [0.12271106 0.15310156 0.87334627]]
After loading, content of the text file:
[[0.096648 0.146422 0.107885]
 [0.19427  0.350024 0.344839]
 [0.122711 0.153102 0.873346]]


In [ ]:
# PANDAS EXCEL

In [ ]:
# Q1

In [35]:
import pandas as pd

In [36]:
# Q1

In [59]:
import pandas as pd
import matplotlib.image as img
import matplotlib.pyplot as plt
image = img.imread('pokemon.jpg')
print( "Image Shape: " , image.shape)

if(image.shape[2] == 3) :
  image_reshape = image.reshape(image.shape[0],-1)
  print("Reshaping to 2D array:" , image_reshape.shape)
else:
  # remain as it is
  image_reshape = imageMat
      
# converting it to dataframe.
mat_df = pd.DataFrame(image_reshape)
  
# exporting dataframe to CSV file.
mat_df.to_csv('file.csv',
              header = None,
              index = None)
loaded_df = pd.read_csv('file.csv', 
                        sep = ',',
                        header = None)
# getting matrice values.
loaded_2D_mat = loaded_df.values
  
# reshaping it to 3D matrice
loaded_mat = loaded_2D_mat.reshape(loaded_2D_mat.shape[0],
                                   loaded_2D_mat.shape[1] // image.shape[2],
                                   image.shape[2])
  
print("Image shape of loaded Image :",
      loaded_mat.shape)
  
# check if both matrice have same shape or not
if((image == loaded_mat).all()):
  print("\n\nYes",
        "The loaded matrice from CSV file is same as original image matrice")


Image Shape:  (800, 1200, 3)
Reshaping to 2D array: (800, 3600)
Image shape of loaded Image : (800, 1200, 3)


Yes The loaded matrice from CSV file is same as original image matrice


In [ ]:
#Q2

In [60]:
mydata = pd.read_csv("file.csv")
df = pd.DataFrame(data=mydata)
df1 = df.iloc[:-1,:-1]
print(df1)

     249  225  221  249.1  225.1  221.1  249.2  225.2  221.2  249.3  ...  \
0    249  225  221    249    225    221    249    225    221    249  ...   
1    249  225  221    249    225    221    249    225    221    249  ...   
2    249  225  221    249    225    221    249    225    221    249  ...   
3    249  225  221    249    225    221    249    225    221    249  ...   
4    249  225  221    249    225    221    249    225    221    249  ...   
..   ...  ...  ...    ...    ...    ...    ...    ...    ...    ...  ...   
793  249  225  221    249    225    221    249    225    221    249  ...   
794  249  225  221    249    225    221    249    225    221    249  ...   
795  249  225  221    249    225    221    249    225    221    249  ...   
796  249  225  221    249    225    221    249    225    221    249  ...   
797  249  225  221    249    225    221    249    225    221    249  ...   

     225.1196  221.1196  249.1197  225.1197  221.1197  249.1198  225.1198  \
0         

In [ ]:
# Q3

In [52]:
import pandas as pd
from datetime import date
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2021-08-08 00:00:00


In [ ]:
# Q3 Age Calculator

In [55]:
from datetime import date

def age_calc(dob):
    today = date.today()
    return today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
print(age_calc(date(1998,6,10)))


23
